apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
  labels:
    app: $APP_NAME
    env: $ENV_NAME
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: $APP_NAME
        env: $ENV_NAME
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: $APP_NAME
        image: $IMAGE_NAME
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: $SECRET_NAME
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: $SECRET_NAME
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: $CONFIG_NAME
                key: AWS_REGION
          - name: CW_LOG_GROUP
            valueFrom:
              configMapKeyRef:
                name: $CONFIG_NAME
                key: CW_LOG_GROUP
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
