kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-cloudwatch-config
  namespace: kube-system
data:
  aws_region: eu-west-1
  log_group: kubernetes-cluster

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-cloudwatch-v1
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluentd-cloudwatch
        image: callstats/fluentd-kubernetes-cloudwatch:v1.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: fluentd-secrets
                key: aws_access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fluentd-secrets
                key: aws_secret_key
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: fluentd-cloudwatch-config
                key: aws_region
          - name: CW_LOG_GROUP
            valueFrom:
              configMapKeyRef:
                name: fluentd-cloudwatch-config
                key: log_group
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
